spring.application.name=projeto-spring-api

spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_spring
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

app.jwt.secret=01234567890123456789012345678901
app.jwt.expiration-minutes=120
